### ISSUE TITLE
"Full Size" UV causes crash

### ISSUE THREAD

**Issue by Daniel99j2** [tomalbrc/Sandstorm#2]
When using Full Size UV, a crash occurs as in snowstorm, when it is full size uv, the uv value is removed:
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'magma-network-mod' at 'com.daniel99j.magmanetwork.MagmaNetworkMod'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at knot//net.minecraft.client.MinecraftClient.<init>(MinecraftClient.java:533)
	at knot//net.minecraft.client.main.Main.main(Main.java:212)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)
Caused by: java.lang.NullPointerException: Cannot read field "uv" because "billboard.uv" is null
	at knot//de.tomalbrc.sandstorm.util.ParticleModels.handleUV(ParticleModels.java:98)
	at knot//de.tomalbrc.sandstorm.util.ParticleModels.addFrom(ParticleModels.java:82)
	at knot//de.tomalbrc.sandstorm.Particles.loadEffect(Particles.java:52)
	at knot//de.tomalbrc.sandstorm.Particles.loadEffect(Particles.java:65)
	at knot//com.daniel99j.magmanetwork.MagmaNetworkMod.onInitialize(MagmaNetworkMod.java:196)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399)
	... 7 more

Full Size:
			"minecraft:particle_appearance_billboard": {
				"size": ["(variable.particle_random_1+1)/3", "(variable.particle_random_1+1)/3"],
				"facing_camera_mode": "rotate_xyz"
			},
			
Static mode:
			"minecraft:particle_appearance_billboard": {
				"size": ["(variable.particle_random_1+1)/3", "(variable.particle_random_1+1)/3"],
				"facing_camera_mode": "rotate_xyz",
				"uv": {
					"texture_width": 16,
					"texture_height": 16,
					"uv": [0, 0],
					"uv_size": [16, 16]
				}
			},

**Comment by tomalbrc** [comment]
Fixed in 0.2.0-beta.1
